#!/bin/bash
git branch | grep "\* master"

if [ $? != 0 ]; then
	echo "********** WARNING! Not in MASTER branch! **********"
	echo "             Press Ctrl-C now to abort"
	sleep 5
fi
echo "shutting down dev myna"
./dev_server stop
echo "building JS docs..."
sh update_docs

if [ -e  build.dev ]; then
	mv build.dev build.dev.`date  +%m-%d-%Y.%H.%M.%S`
fi

echo "Moving dev build directory..."
mv build build.dev

ant dist
if [ -e  build.dev ]; then
	echo "restoring dev build directory..."
	rm -rf build.dist && mv build build.dist && mv build.dev build
fi


git status
read -p "Commit changes and update tags? [y/N]" shouldCommit

if [ "$shouldCommit" == "y" ]; then
	git commit -a -m "version number update"
	git tag `cat src/version.properties | cut -d= -f2`
	git push origin --tags
fi

echo "Done with Build, restarting dev server"
./dev_server restart
