#!/bin/bash
#
# Myna Main instance Control Script
#

#Make sure that the webroot owner matches this
user="{user}"
server="{server}"
context="{webctx}"
#set this to 0 to disable http
port={port}

webroot="{webroot}"
logfile="{logfile}"
mem=256
ps_signature="java.*myna.name=$server"
export JAVA_HOME="{javahome}"
#export JRE_HOME=/usr/java/default/jre/
web_inf=$(readlink -m $webroot/WEB-INF)

#SSL
#set this to something non-zero to enable https
ssl_port={sslPort}
keystore="{keystore}"
ks_pass="{ksPass}"
ks_alias="{ksAlias}"


myna_cp="-cp $web_inf/lib/*:$web_inf/classes/:/usr/local/bin"

#	watchdog_jvm_args
watchdog_jvm_args="\
	-Dmyna.name=$server \
	-Xmx20m \
	-server \
	$myna_cp "

#	server_jvm_args	
server_jvm_args="\
	-Djava.security.egd=file:/dev/./urandom \
	-Dmyna.name=$server \
	-Xmx${mem}m \
	-server "


#	no_watchdog_args	
no_watchdog_args="\
	$myna_cp\
	-Dmyna.hasWatchdog=true"

#	myna_args	
myna_args="\
	-m server \
	-c $context \
	-p $port \
	-sp $ssl_port \
	-ks $keystore \
	-ksp $ks_pass \
	-ksa $ks_alias \
	-w $webroot \
	-l $logfile "


case "$1" in
start)
	su $user -l -c "java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args -- $server_jvm_args"&
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
start-nowatchdog)
	su $user -l -c "java  $no_watchdog_args $server_jvm_args info.emptybrain.myna.MynaServer $myna_args"&
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
stop)
	$0 status > /dev/null
	if [ $? -eq 0 ];then
		ps -ef | grep "$ps_signature" | grep -v grep  | awk '{print $2}' | xargs kill  &> /dev/null
		sleep 2
		$0 status > /dev/null
		if [ $? -eq 0 ];then
			ps -ef | grep "$ps_signature" | grep -v grep  | awk '{print $2}' | xargs kill -9  &> /dev/null
		fi
		echo "Myna instance '$server' stopped."
	else
		echo "Myna instance '$server' is not running."
	fi
	
    ;;

restart)
   $0 stop
	sleep 1
	$0 start
    ;;
status)
	echo -n Myna instance \"$server\":
	ps -ef | grep "$ps_signature" | grep -v grep > /dev/null 
	if [ $? -eq 0 ];then
		echo " Running."
		exit 0
	else
		echo " Stopped."
		exit 1
	fi
   
    ;;
*)
    echo "usage: $0 (start|stop|restart|status)"
esac


