#!/bin/bash
#
# Myna Main instance Control Script
#

#Make sure that the webroot owner matches this
user="{user}"
server="{server}"
context="{webctx}"
port={port}
webroot="{webroot}"
logfile="{logfile}"
mem=256
ps_signature="java.*myna.name=$server"
export JAVA_HOME="{javahome}"
#export JRE_HOME=/usr/java/default/jre/

web_inf=$(readlink -m $webroot/WEB-INF)

case "$1" in
start)
	watchdog_jvm_args="-Dmyna.name=$server -Xmx20m -server -cp $web_inf/lib/*:$web_inf/classes/"
	server_jvm_args="-Dmyna.name=$server -Xmx${mem}m -server"
	
	myna_args="-c $context -p $port -w $webroot -l $logfile -- $server_jvm_args"
	su $user -l -c "java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args "&
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
start-nowatchdog)
	watchdog_jvm_args="-Dmyna.name=$server -Xmx${mem}m -Dmyna.hasWatchdog=true -server -cp $web_inf/lib/*:$web_inf/classes/"
	
	
	myna_args="-c $context -p $port -w $webroot -l $logfile "
	su $user -l -c "java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args "&
	#java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args &
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
stop)
	$0 status > /dev/null
	if [ $? -eq 0 ];then
		ps -ef | grep "$ps_signature" | grep -v grep  | awk '{print $2}' | xargs kill  &> /dev/null
		sleep 2
		$0 status > /dev/null
		if [ $? -eq 0 ];then
			ps -ef | grep "$ps_signature" | grep -v grep  | awk '{print $2}' | xargs kill -9  &> /dev/null
		fi
		echo "Myna instance '$server' stopped."
	else
		echo "Myna instance '$server' is not running."
	fi
	
    ;;

restart)
   $0 stop
	sleep 1
	$0 start
    ;;
status)
	echo -n Myna instance \"$server\":
	ps -ef | grep "$ps_signature" | grep -v grep > /dev/null 
	if [ $? -eq 0 ];then
		echo " Running."
		exit 0
	else
		echo " Stopped."
		exit 1
	fi
   
    ;;
*)
    echo "usage: $0 (start|stop|restart|status)"
esac


