#!/bin/bash
#
# Myna Main instance Control Script
#

#user=
server=dev
port=8180
myna_home=./build
web_inf=$(readlink -m $myna_home/WEB-INF)

# these are  relative to myna_home or absolute
pidfile=$server.pid
logfile="$(readlink -m $myna_home/..)/$server.log"

jvm_args="-DINST=$server -server -Xmx56m  -Dsun.io.useCanonCaches=false -XX:MaxPermSize=64m -XX:+UseParallelGC -Djava.awt.headless=true"

args="-c /$server -p $port"


#export JAVA_HOME=/usr/java/default/
#export JRE_HOME=/usr/java/default/jre/


case "$1" in
start)
	
	java $jvm_args -cp $web_inf/lib/*:$web_inf/classes/ info.emptybrain.myna.MynaServer $args &> $logfile  &
	pid=$(pgrep -f "^java.*INST=$server")
	#echo $pid > $pidfile
	
	echo "Myna instance '$server' pid ($pid) Starting. tail -f $logfile for details."
	
	exit 0
    ;;
stop)
	
	kill -9 $(pgrep -f ^java.*INST=$server)
	#rm $pidfile
	echo "Myna instance '$server' stopped."
    ;;
compile)
	$0 stop
   ant compile && $0 restart && tail -f $logfile
    ;;
restart)
   $0 stop
	sleep 1
	$0 start
    ;;
status)
	cd $myna_home
	echo -n Myna instance \"$server\":
	$(pgrep -f ^java.*webroot=$webroot 2> /dev/null) 
	if [ $? -eq 0];then
		echo " Running."
	else
		echo " Stopped."
	fi
   
    ;;
*)
    echo "usage: $0 (start|stop|restart|status)"
esac


