#!/bin/bash
#
# Myna Main instance Control Script
#

#user=
server=dev
port=8180
myna_home=./build
web_inf=$(readlink -m $myna_home/WEB-INF)

# these are  relative to myna_home or absolute
pidfile=$server.pid
logfile="$(readlink -m $myna_home/..)/$server.log"

jvm_args="-Dmyna.name=$server -server -Xmx70m"
myna_args="-c /$server -p $port -w $myna_home -l $logfile -- $jvm_args"


#export JAVA_HOME=/usr/java/default/
#export JRE_HOME=/usr/java/default/jre/


case "$1" in
start)
	java  $jvm_args -cp $web_inf/lib/*:$web_inf/classes/ bootstrap.MynaServer $myna_args &
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
stop)
	
	kill -9 $(pgrep -f "^java.*myna.name=$server")
	#rm $pidfile
	echo "Myna instance '$server' stopped."
    ;;
compile)
	$0 stop
   ant compile && $0 restart && tail -f $logfile
    ;;
restart)
   $0 stop
	sleep 1
	$0 start
    ;;
status)
	cd $myna_home
	echo -n Myna instance \"$server\":
	$(pgrep -f "^java.*myna.name=$server" 2> /dev/null) 
	if [ $? -eq 0];then
		echo " Running."
	else
		echo " Stopped."
	fi
   
    ;;
*)
    echo "usage: $0 (start|stop|restart|status)"
esac


