#!/bin/bash
#
# Myna Main instance Control Script
#

#user=
server=dev
mem=512
port=8180
myna_home=./build
web_inf=$(readlink -m $myna_home/WEB-INF)
logfile="$(readlink -m $myna_home/..)/$server.log"
ps_signature="java.*myna.name=$server"
#export JAVA_HOME=/usr/java/default/
#export JRE_HOME=/usr/java/default/jre/

case "$1" in
start)
	watchdog_jvm_args="-Dmyna.name=$server -Xmx20m -server -cp $web_inf/lib/*:$web_inf/classes/:/usr/local/bin"
	server_jvm_args="-Dmyna.name=$server -Xmx${mem}m -server"
	
	myna_args="-m server -c /$server -p $port -w $myna_home -l $logfile -- $server_jvm_args"
	java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args &
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
start-nowatchdog)
	watchdog_jvm_args="-Dmyna.name=$server -Xmx${mem}m -Dmyna.hasWatchdog=true -server -cp $web_inf/lib/*:$web_inf/classes/:/usr/local/bin"
	
	
	myna_args="-m server -c /$server -p $port -w $myna_home -l $logfile "
	java  $watchdog_jvm_args  info.emptybrain.myna.MynaServer $myna_args &
	echo "Myna instance '$server' Starting. tail -f $logfile for details."
	
	exit 0
    ;;
stop)
	
	kill -9 $(pgrep -f "$ps_signature")
	#rm $pidfile
	echo "Myna instance '$server' stopped."
    ;;
compile)
	$0 stop
   ant compile && $0 start-nowatchdog && tail -f $logfile
    ;;
restart)
   $0 stop
	sleep 1
	$0 start
    ;;
status)
	cd $myna_home
	echo -n Myna instance \"$server\":
	pgrep -f "$ps_signature" > /dev/null 
	if [ $? -eq 0 ];then
		echo " Running."
	else
		echo " Stopped."
	fi
   
    ;;
*)
    echo "usage: $0 (start|stop|restart|status)"
esac


